name: Pipeline DevOps

on:
  push:

jobs:
  revisar-html:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias necesarias
        run: npm install -g htmlhint

      - name: Ejecutar prueba de Linter
        run: htmlhint index.html
